# Generated by Django 3.2.5 on 2021-07-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottler', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottler',
            name='bottler_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
